### PR TITLE
Bump 2.63.x to stable release

### PR DESCRIPTION
**Pull request by apolcyn**
cc @JamesNK

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]

**Comment by apolcyn** [comment]
@JamesNK there seems to be something broken in the grpc-web tests.

Can you confirm if it's ok to merge over it?

**Comment by WeihanLi** [comment]
The CI error seems caused by the unmatched dotnet sdk version when building container image, the global json expects `8.0.200` but installed the latest
image

I tried to configure the `rollForward` behavior in `global.json` to fix it in #2437

**Comment by apolcyn** [comment]
@JamesNK opened https://github.com/grpc/grpc-dotnet/pull/2442

**Comment by apolcyn** [comment]
cc @stanley-cheung

**Pull request merged**
