### PR TITLE
Add gRPC-Web Blazor interop tests

### PR DESCRIPTION
**Pull request by JamesNK**
Also a minor fix to include endpoint metadata on unimplemented endpoints so they will pick up CORS metadata.

@stanley-cheung

TODO:

- [x] Documentation about the various test apps and how to call them, including the new gRPC-Web apps
- [x] Integration with a JS test framework?

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Changes LGTM so far, do you plan on adding more to this PR?

**Comment by JamesNK** [comment]
Possibly integrate with JS test framework.

**Comment by stanley-cheung** [comment]
@JamesNK Is `testassets/README.md` the entry point I should look into this PR? I should be able to run those `docker-compose` commands if I patch in this PR right? Can you also give me a bit more background on Blazor please? I remember you mention that this is a conduit for the client side tests to be run but I was a little bit fuzzy on the details. Can you explain a little bit more please? Thanks!

**Comment by JamesNK** [comment]
> Is testassets/README.md the entry point I should look into this PR? I should be able to run those docker-compose commands if I patch in this PR right?

Yes.

> Can you also give me a bit more background on Blazor please?

[Blazor is a WebAssembly framework.](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor) When the webpage in the client loads, it will load the Blazor WebAssembly app and run the tests in JavaScript. Each JavaScript test calls into Blazor to make the gRPC-Web call and assert the results.

**Comment by stanley-cheung** [comment]
> Each JavaScript test calls into Blazor to make the gRPC-Web call and assert the results.

Can you point me to where in this PR that happens please?

**Comment by JamesNK** [comment]
Calling JavaScript on web page: https://github.com/JamesNK/grpc-dotnet/blob/jamesnk/grpcweb-interop/testassets/InteropTestsGrpcWebClient/wwwroot/index.html#L69

Called C# in Blazor: https://github.com/JamesNK/grpc-dotnet/blob/jamesnk/grpcweb-interop/testassets/InteropTestsGrpcWebClient/Pages/Index.razor.cs#L52

**Comment by JamesNK** [comment]
This PR is complete.

@stanley-cheung Tests are now automated. See grpcweb_interoptests.sh for running them

@jtattermusch Is it possible to have the grpcweb interop tests run parallel to the existing build? At the moment build_and_test.sh is calling grpcweb_interoptests.sh. It would be nice if we could make grpcweb_interoptests.sh run by itself since it doesn't depend on anything.

@JunTaoLuo Please review.

**Comment by stanley-cheung** [comment]
@JamesNK I must be missing something obvious: when I run `grpcweb_interoptests.sh` (by the way, when I clone the repo, the script wasn't executable, I did a `chmod +x`), all the tests failed with `Evaluation failed: ReferenceError: host is not defined`. Perhaps I have to set an env var somewhere?

**Comment by JamesNK** [comment]
`Evaluation failed: ReferenceError: host is not defined`

Where do you get that error? Inside the execution of a test? Is any more detail you can provide?

It works on my machine and it works on the build server 🤷

**Comment by stanley-cheung** [comment]
@JamesNK Great, your latest changes fixed it. I am able to run the entire thing successfully!

**Comment by jtattermusch** [comment]
> This PR is complete.
> 
> @stanley-cheung Tests are now automated. See grpcweb_interoptests.sh for running them. It should be simple enough to clone the repo and then run grpcweb Blazor client against a different server, or a different grpcweb client against the server.
> 
> @jtattermusch Is it possible to have the grpcweb interop tests run parallel to the existing build? At the moment build_and_test.sh is calling grpcweb_interoptests.sh. It would be nice if we could make grpcweb_interoptests.sh run by itself since it doesn't depend on anything.
> 
> @JunTaoLuo Please review.

We can look into running grpcweb_interoptests.sh in a separate test job as a followup.

**Pull request merged**
