### PR TITLE
Add myself to maintainers list

### PR DESCRIPTION
**Pull request by anurse**
cc @JunTaoLuo @JamesNK

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @anurse isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by anurse** [comment]
Working on the CLA ;).

**Comment by srini100** [comment]
cc @a11r

**Comment by anurse** [comment]
CLA should be signed now!

**Comment by jtattermusch** [comment]
@a11r @srini100 : Majority of current maintainers have agreed to add @anurse as maintainer.

**Comment by anurse** [comment]
Do I need to do anything for the EasyCLA thing? I did the Linux Foundation one (which was approved by our legal group) but I'm not sure about the EasyCLA one :).

**Comment by jtattermusch** [comment]
@anurse   AFAIK the EasyCLA should be the same kind of CLA from the legal perspective, it's just a new bot that manages it (both bots are provided by CNCF).

**Comment by anurse** [comment]
Gotcha. Did that one as well then just to make sure all is good to go if I need to contribute code/docs/etc. later ;).

**Pull request merged**
