### PR TITLE
Update version to 2.56.0 (on v2.56.x branch)

### PR DESCRIPTION
**Pull request by jtattermusch**
I'll publish the release on/after Aug 23 if everything looks good.

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]

**Comment by jtattermusch** [comment]
Nugets pushed, release published: https://github.com/grpc/grpc-dotnet/releases/tag/v2.56.0

**Comment by tomkerkhove** [comment]
It might be beneficial to update the release with an overview of changes since last stable version and not preview as it currently is a bit vague:
image

**Comment by jtattermusch** [comment]
> It might be beneficial to update the release with an overview of changes since last stable version and not preview as it currently is a bit vague: image

Fair point, but we'd have to update all the past releases as well for consistency, since this is the way we'd been structuring the release notes for a quite a long time now (basically, the full changelog of the stable release is the changelog since the last pre-release AND all the release notes of all the previous pre-releases).

**Comment by tomkerkhove** [comment]
That's OK - But what about upcoming releases? Can we please start using a more end-user friendly way? Otherwise you have to go through every single preview that was done to understand what changed which adds a lot of cognitive load

**Pull request merged**
