### PR TITLE
Update version to 2.46.0 (on v2.46.x)

### PR DESCRIPTION
**Pull request by jtattermusch**
I will publish the stable release once this is approved and merged.

### CODE REVIEW

**Comment by JamesNK** [comment]
GrpcPackageVersion in dependencies.prop needs to be updated to 2.46.0 on this branch

**Review by JamesNK — CHANGES_REQUESTED** [review]
GrpcPackageVersion in dependencies.prop needs to be updated to 2.46.0 on this branch

**Comment by jtattermusch** [comment]
> GrpcPackageVersion in dependencies.prop needs to be updated to 2.46.0 on this branch

Done

**Review by JamesNK — APPROVED** [review]

**Comment by jtattermusch** [comment]
The interop test failure is because we didn't backport https://github.com/grpc/grpc-dotnet/pull/1721 into the 1.46.x branch.

**Comment by jtattermusch** [comment]
Nugets were pushed, release is here: https://github.com/grpc/grpc-dotnet/releases/tag/v2.46.0

**Pull request merged**
