### PR TITLE
Add version conditions for Microsoft.Extensions.Http and Microsoft.Extensions.Logging.Abstractions

### PR DESCRIPTION
**Pull request by ArminShoeibi**
This merge request adds some conditions in Grpc.Net.Client.csproj and Grpc.Net.ClientFactory.csproj.
Actually, this merge request solves this problem.

image

Thank you in advance.

### CODE REVIEW

**Comment by JamesNK** [comment]
What does this fix? The older version is forward compatible, and a .NET 6 app can specify to use version 6 of that Microsoft.Extensions library if it wants.

**Comment by ArminShoeibi** [comment]
> What does this fix? The older version is forward compatible, and a .NET 6 app can specify to use version 6 of that Microsoft.Extensions library if it wants.

Yes, you told me this before, but not everyone knows this.
They just install without attention, by the way with this merge request we don't need to install those packages explicitly.

**Comment by JamesNK** [comment]
Ok. Usually referencing the lowest version is recommended. However, there are some advantages of bringing in a new version.

Let me talk with some other .NET people. I will see what the general approach is here.

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/pull/2021 updates the dependencies to .NET 6

**Pull request closed without merging**
