### PR TITLE
Bump Grpc.Tools version to 2.65.0

### PR DESCRIPTION
**Pull request by stanley-cheung**
Bump Grpc.Tools version on `master` to `2.65.0`

### CODE REVIEW

**Comment by stanley-cheung** [comment]
The Nuget Build failed with this log messages:

```
+ dotnet pack --configuration Release --output ../../artifacts -p:ContinuousIntegrationBuild=true

Welcome to .NET 9.0!
---------------------
SDK Version: 9.0.100-preview.5.24305.3

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate, view the instructions: https://aka.ms/dotnet-https-linux

----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  Determining projects to restore...
  Failed to restore /tmpfs/src/github/grpc-dotnet/src/Grpc.Core.Api/Grpc.Core.Api.csproj (in 750 ms).
  Failed to restore /tmpfs/src/github/grpc-dotnet/src/Grpc.Auth/Grpc.Auth.csproj (in 1.11 sec).
/tmpfs/src/github/grpc-dotnet/.dotnet/sdk/9.0.100-preview.5.24305.3/NuGet.targets(170,5): error MSB4181: The "RestoreTask" task returned false but did not log an error. [/tmpfs/src/github/grpc-dotnet/src/Grpc.Auth/Grpc.Auth.csproj]
```

Perhaps related to #2457?

**Comment by JamesNK** [comment]
It might be a transient error. I suggest retrying.

**Comment by stanley-cheung** [comment]
I re-tried twice but I am getting these errors now instead

```
/tmpfs/src/github/grpc-dotnet/src/Grpc.Auth/Grpc.Auth.csproj : error NU1301: Unable to load the service index for source [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json](https://www.google.com/url?q=https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json&sa=D).
/tmpfs/src/github/grpc-dotnet/src/Grpc.Auth/Grpc.Auth.csproj : error NU1301: Unable to load the service index for source [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json](https://www.google.com/url?q=https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json&sa=D).
/tmpfs/src/github/grpc-dotnet/src/Grpc.Auth/Grpc.Auth.csproj : error NU1301: Unable to load the service index for source [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json](https://www.google.com/url?q=https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json&sa=D).
/tmpfs/src/github/grpc-dotnet/src/Grpc.Auth/Grpc.Auth.csproj : error NU1301: Unable to load the service index for source [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json](https://www.google.com/url?q=https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json&sa=D).
/tmpfs/src/github/grpc-dotnet/src/Grpc.Auth/Grpc.Auth.csproj : error NU1301: Unable to load the service index for source [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json](https://www.google.com/url?q=https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json&sa=D).
/tmpfs/src/github/grpc-dotnet/src/Grpc.Auth/Grpc.Auth.csproj : error NU1301: Unable to load the service index for source [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json](https://www.google.com/url?q=https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json&sa=D).
```

Still probably transient?

**Comment by JamesNK** [comment]
I think there is an ongoing outage for the site that hosts the package feed in the error message.

**Comment by JamesNK** [comment]
https://status.dev.azure.com/_event/524064579

**Comment by stanley-cheung** [comment]
> https://status.dev.azure.com/_event/524064579

🤦 lucky me...

Thanks for the link. Will monitor and then retry

**Comment by stanley-cheung** [comment]
@JamesNK Looks like the outage is over. I retried the job and now it passed. Thanks.

**Review by JamesNK — APPROVED** [review]

**Pull request merged**
