### PR TITLE
Refactor client factory to support per-instance interceptors and scoped DI

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/grpc/grpc-dotnet/issues/842

This PR makes it possible to have interceptor instances created for each client instance created.

Note that there is a behavior change. Previously a single interceptor instance was the default. The new default behavior is to create a new interceptor each time. Lifetime can be controlled by explicitly defining how an interceptor is created by DI.

```cs
services
  .AddGrpcClient<Greeter.GreeterClient>(o => o.Address = new Uri("http://localhost"))
  .AddInterceptor<CallbackInterceptor>();

// Make interceptor a singleton
services.AddSingleton<CallbackInterceptor>();
```

### CODE REVIEW

**Comment by JamesNK** [comment]
I want to wait on merging this PR.

I'm worried about GrpcChannelOptions and how we currently recreate the channel for each client. That works today because we reuse a HttpClient, which is were most of the cost is, but I worry about future features like load balancing. Load balancing has state so we'd want to persist a channel for the lifetime of the HttpClient. Should ensure this problem is solved before committing this PR and potentially putting ourselves in a corner.

**Comment by JamesNK** [comment]
Will revisit in the future.

**Comment by diogonborges** [comment]
Sorry if I'm being redundant but does this mean that currently the only supported Lifetime is Singleton?

**Comment by murrays** [comment]
Guys this is causing us real issues. The problem is that we can't access the current 'scope' to manage per request options like tenancy.  We are intercepting client calls and the intention was to pull from a scoped object containing per request items and stuffing  into the headers.  However when we inject the scoped object (i.e. added to container via TryAddScoped() we always get the global instance.  I am now having to get clients to add in header stuff manually which is error prone and not that great.  James, are you still looking at a fix for this?

**Comment by JamesNK** [comment]
I'll revisit this once load balancing is supported.

If using the client factory isn't a good solution then create channels and clients, and register them in DI, yourself.

**Pull request closed without merging**
