### PR TITLE
Functional Tests On Real Kestrel Server and Test Server

### PR DESCRIPTION
**Pull request by thefringeninja**
I've recently run into a problem trying to use `AsyncDuplexStreamingCall` with the kestrel `TestServer`. Communicating from client->server never reaches the server.

While trying to debug this issue I ran across aspnet/AspNetCore#11598. I understand the need to test a library like this as close to real world conditions as possible. However, I see no reason not to test _both_ at the same time.

As stated in the aforementioned thread, socket exhaustion is a real problem on macOS. Our tests are naturally stateful, so we really need to test against a fresh instance every time. In fact, socket exhaustion on macOS is what lead us to implement a gRPC solution in the first place! We had assumed everything would work through the `TestServer`.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @thefringeninja isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @thefringeninja isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @thefringeninja isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @thefringeninja isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thefringeninja** [comment]
I signed the linux foundation CLA.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @thefringeninja isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by JamesNK** [comment]
I'm replacing this PR with https://github.com/grpc/grpc-dotnet/pull/624

I want to test running gRPC functional tests with TestServer, but I don't want to duplicate every functional test. I would prefer to test important scenarios and any bugs that show up.

**Pull request closed without merging**
