### PR TITLE
Set nuget version to 0.1.19-pre1

### PR DESCRIPTION
**Pull request by jtattermusch**
I'll merge this later this week once we're ready to cut the prerelease.

After merging, I'll tag (`v0.1.19-pre1`), create the release in https://github.com/grpc/grpc-dotnet/releases  and push the nuget to nuget.org.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Actually hold off on this for a little bit. I ran into an error when updating our templates to use the latest aspnetcore bits. I think we need a fix in our call handlers but I want to be certain I understand the changes.

**Comment by JunTaoLuo** [comment]
Tested with templates and it works with https://github.com/grpc/grpc-dotnet/pull/112 merged. This is ready to be merged and released.

**Comment by JamesNK** [comment]
Before release I think it would be worth re-running the interop tests to make sure #112 didn't introduce any regressions.

**Comment by jtattermusch** [comment]
I tested the changes in #112 with an adhoc interop tests run and everything is passing: (https://source.cloud.google.com/results/invocations/fb8b0b95-5ecb-414e-9429-e1f8b84a8523/targets/github%2Fgrpc%2Finterop_test/tests;query=aspnetcore)
I needed to add a hotfix to the interop testing setup due to the get-dotnet changes (I'll followup on that, but it doesn't influence this release).

**Comment by jtattermusch** [comment]
The nuget package has been pushed to nuget.org:
https://www.nuget.org/packages/Grpc.AspNetCore.Server/0.1.19-pre1

A git tag and github release have been created:
https://github.com/grpc/grpc-dotnet/releases/tag/v0.1.19-pre1

**Pull request merged**
