### PR TITLE
Bump Google.Protobuf to 3.10.0 (#582)

### PR DESCRIPTION
**Pull request by nagytech**
Regarding feature request #582

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by JamesNK** [comment]
Looks good. Need to sort out the CLA before it can be merged.

**Comment by nagytech** [comment]
Sorry, linked the wrong email - hoping this comment will trigger another CLA request.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @nagytech isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by nagytech** [comment]
CLA updated for linuxfoundation

**Pull request merged**
