### PR TITLE
Update version to 2.41.0-pre1 (on the release branch)

### PR DESCRIPTION
**Pull request by jtattermusch**
I will publish the pre-release right after merging this. Let me know if there's any blockers.

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
btw the reason for the failing tests is this line: https://github.com/grpc/grpc-dotnet/blob/530eb1c25c8c37260aaff11cc816adf6a20570f5/test/Grpc.Net.Client.Tests/AsyncUnaryCallTests.cs#L87

The version is one character too long: `2.41.0-pre1`

Change it to `Assert.IsTrue(grpcVersion.Product!.Version!.Length <= 11);`

I'm not sure why this hasn't failed before when the product name goes from `2.41.0-dev` to `2.41.0-pre1`. Something related to the user-agent string update?

**Comment by JamesNK** [comment]
The gRPC package version needs to be updated to 2.41.0?

https://github.com/grpc/grpc-dotnet/blob/530eb1c25c8c37260aaff11cc816adf6a20570f5/build/dependencies.props#L6

**Comment by jtattermusch** [comment]
Test failure should be fixed by https://github.com/grpc/grpc-dotnet/pull/1486

**Comment by JamesNK** [comment]
Needs rebase, then it should pass.

**Comment by jtattermusch** [comment]
@JamesNK I just pushed the nuget packages and created a release:
https://github.com/grpc/grpc-dotnet/releases/tag/v2.41.0-pre1 
(and btw the new "autogenerate release notes" feature didn't seem to generate meaningful contents, so I left the release notes empty for now and they'll need to be filled in by hand).

**Pull request merged**
