### PR TITLE
adding readme for App Service scenarios

### PR DESCRIPTION
**Pull request by btardif**
Calling out changes to App Settings needed to make this work with App Service

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @btardif isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by JamesNK** [comment]
The protocol isn't required for this sample at all.

I think a better change would be to remove it from the json file and leave Kestrel to default to Http1AndHttp2. That should be fine in app service.

**Comment by btardif** [comment]
> The protocol isn't required for this sample at all.
> 
> I think a better change would be to remove it from the json file and leave Kestrel to default to Http1AndHttp2. That should be fine in app service.

ok I'll try that out and confirm.

I'll update the PR if this works

**Comment by AnthonyGiretti** [comment]
Thank you very much. Really helpful, it fixes my issue!

**Pull request closed without merging**
