### PR TITLE
API adjustments for preview2

### PR DESCRIPTION
**Pull request by davidfowl**
- Fixed functional test and unit test

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @davidfowl isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jtattermusch** [comment]
Saw the test failure here: https://travis-ci.org/grpc/grpc-dotnet/builds/488435210

**Comment by jtattermusch** [comment]
@davidfowl  should I merge?

**Comment by davidfowl** [comment]
Yep! I don't have commit rights to the repo 😢

**Pull request merged**
